server:
  port: 8083

spring:
  application:
    name: QUALIFICATION-SERVICE
  config:
    enabled: false
    import: optional:configserver:instead
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservicios

